export const CONSTANTS = {
  ROSTER_DATA_NAME: 'ROSTER_DATA',
  RAW_PITCHER_STATS: 'RAW_PITCHER_STATS',
  RAW_HITTER_STATS: 'RAW_HITTER_STATS',
  ROSTER_STATS: 'ROSTER_STATS',
  RAW_POS_STATS: 'RAW_POS_STATS',
  GRAND_TOTALS_HISTORY: 'GRAND_TOTALS_HISTORY',
  STALE_STATS_TIME_GAP: 20000
};